### ISSUE TITLE
projectable-kill-project-buffers shouldn't attempt to kill non-existent buffers

### ISSUE THREAD

**Issue by AlexChesters** [domtronn/projectable.el#25]
For example if `projectable-get-project-buffers` returns an empty list, it would be nicer IMO if we did something along the lines of `(message "You don't have any open buffers associated with a project file")` or something along those lines.

**Comment by domtronn** [comment]
So I think this is fixed and improved massively now, are you happy @AlexChesters?

**Comment by AlexChesters** [comment]
itest

**Comment by AlexChesters** [comment]
Just had a go and it seems good to me! :+1:
