### ISSUE TITLE
Ability to quickly open project configuration

### ISSUE THREAD

**Issue by AlexChesters** [domtronn/projectable.el#3]
Sometimes when I'm working in a project I'd like to be able to quickly make a change to my `project-name.json` file without having to navigate to it myself. It would be nice to have something like `projectable-open-config` which quickly opened the active config file

**Comment by domtronn** [comment]
This should be quite easy to do, we have a variable defined as `projectable-current-project-path` which stores the path to the _project json file_ or the _anonymous directory_ it has loaded.

All we would need to do is check if it _is_ a file and then call `find-file` on it.

**Comment by domtronn** [comment]
Resolved as above.
