### ISSUE TITLE
Changing to a project without a gitignore errors

### ISSUE THREAD

**Issue by AlexChesters** [domtronn/projectable.el#32]
To reproduce:
1. `mkdir foo`
2. `projectable-change` into this directory
3. Observe the error `Opening input file: no such file or directory, /Users/chesta02/Desktop/code/tal-app/.gitignore`

**Comment by domtronn** [comment]
I can't seem to reproduce this?

**Comment by AlexChesters** [comment]
@domtronn are you making a project file or trying to change directly into the directory?

**Comment by domtronn** [comment]
Change directly into the directory, so my actions including key presses were like this

``` elisp
M-x mkdir "~/code/foo" RET
C-x p c "~/code/foo" C-j
;; OR
projectable-change "~/code/foo" C-j
```

Does that make sense?

**Comment by AlexChesters** [comment]
Closing this as I haven't been able to reproduce it since
