### ISSUE TITLE
Feature: Ability to pull down changes easily

### ISSUE THREAD

**Issue by AlexChesters** [domtronn/projectable.el#4]
If I'm working on a project with multiple files, it would be nice if there was a simple command to pull down changes into all of my project folders, something like `projectable-pull` which did a simple `git pull` into all of my project folders

**Comment by domtronn** [comment]
Sorry @AlexChesters, this isn't really the responsibility of this package, it's designed to make _navigating_ projects easier.

And most of the time, projects only consist of a single repo.
