### ISSUE TITLE
Ability to use projectable with SVN repos

### ISSUE THREAD

**Issue by AlexChesters** [domtronn/projectable.el#7]
I believe this would be as simple as setting [this](https://github.com/domtronn/projectable.el/blob/master/projectable.el#L63) to false if you are using an SVN repo @domtronn?

**Comment by domtronn** [comment]
I'm guessing this is to do with the fact you have SVN repos checked out within a Git project which ignores the SVN repo so you don't commit it to the Git project.

This has nothing to do with the projectable's ability to work with SVN repos, to be honest, this is an odd situation...

However, yes, setting that variable to false will stop the exclusion of the SVN repos, if you add it to your custom variables as nil that should fix it.

Perhaps it would be worth adding the ability to set projectable variables, or at least declare their value, from within the JSON files.

That way you could have it change per project?

**Comment by AlexChesters** [comment]
Hmmm, yes good point @domtronn.. title of this issue should probably be changes. Given that this is a very unusual situation and the fact that there is a custom variable for this then maybe that's fine

**Comment by domtronn** [comment]
So, I've added in the ability to override the `gitignore` property on a project by project basis... So this should fix this weird issue if you happen to have an svn repo inside a git repository that ignores the repos in the `.gitignore` file...

This might be a normal set up for sandboxes or the like...
