### ISSUE TITLE
New Name

### ISSUE THREAD

**Issue by domtronn** [domtronn/projectable.el#8]
I'm bad at naming things, and I'm not overly attached to the name of this project... New ideas for the name would be great!

**Comment by subsidel** [comment]
Idea: cloned/repo

**Comment by AlexChesters** [comment]
http://pungenerator.org/puns?q=project

**Comment by AlexChesters** [comment]
POP (Project-oriented programming)*

*disclaimer, I got this from a pun website.

**Comment by domtronn** [comment]
How about Jpop? Json Project Oriented (Something beginning with P)?

**Comment by domtronn** [comment]
**JPop** - **J**son **P**ortrayal **o**f **P**rojects

**Comment by AlexChesters** [comment]
JPoP :+1:

**Comment by AlexChesters** [comment]
Looks good, just need to rename the repo now

**Comment by domtronn** [comment]
I think everything's renamed now, including this repo... I'm going to close this
